#!/bin/bash
########################################################################################################################
#
# This script is used to manage a Ping Identity DevOps environment for Docker, Docerk Compose and Kubernetes.
#
# ------------
# Installation
# ------------
#   brew install ping-devops
#   brew upgrade ping-devops
#
# ------------
# Requirements
# ------------
# The script requires the following tools to be installed:
JQ="jq"
BASE64="base64"
OPENSSL="openssl"
KUSTOMIZE="kustomize"
KUBECTL="kubectl"
KUBECTX="kubectx"
KUBENS="kubens"
ENVSUBST="envsubst"
DOCKER="docker"
DOCKER_COMPOSE="docker-compose"
CURL="curl -sL "
#
# In addition, the assumption is that kubectl is configured to authenticate and apply manifests to the Kubernetes
# cluster. For EKS clusters, this requires an AWS key and secret with the appropriate IAM policies to be configured and
# requires that the aws CLI tool and probably the aws-iam-authenticator CLI tool are installed.
#
# Information on all the Variables can be found at:
#    ping-devops topic devops-variables
########################################################################################################################

CWD=`pwd` 
cd "$( dirname "${0}" )"
THIS="$( basename "${0}" )"
THIS_DIR=`pwd`

PING_DEVOPS_STANDARD_VARIABLES="
  PING_IDENTITY_DEVOPS_USER
  PING_IDENTITY_DEVOPS_KEY
  PING_IDENTITY_DEVOPS_HOME
  PING_IDENTITY_DEVOPS_REGISTRY
  PING_IDENTITY_DEVOPS_TAG
  PING_IDENTITY_ACCEPT_EULA"

################################################################################
# Version Info
################################################################################
VERSION="0.5.7"

################################################################################
# Ping Identity tools & config information
################################################################################
DOT_PINGIDENTITY="${HOME}/.pingidentity"
DEVOPS_FILE="${DOT_PINGIDENTITY}/devops"
PRINT_DEVOPS_FILE="~/.pingidentity/devops"
DEVOPS_WORK_DIR="${DOT_PINGIDENTITY}/ping-devops"
test -d "${DEVOPS_WORK_DIR}" || mkdir -p "${DEVOPS_WORK_DIR}"

################################################################################
# Ping DevOps URL & Info
################################################################################
# Note: bit.ly URLs require a header to be be passed in curl (i.e. -H "User-Agent: ping-devops")
PING_DEVOPS_URL="https://bit.ly/ping-devops-json"
PING_DEVOPS_JSON="${DEVOPS_WORK_DIR}/.ping-devops.json"
PING_DEVOPS_GITHUB_CONTENT="https://raw.githubusercontent.com/pingidentity/pingidentity-devops-getting-started/master"
PING_DEVOPS_TOPICS_URL="${PING_DEVOPS_GITHUB_CONTENT}/docs/ping-devops/topics"
PING_DEVOPS_TOPICS_JSON_URL="https://api.github.com/repos/pingidentity/pingidentity-devops-getting-started/contents/docs/ping-devops/topics"
PING_DEVOPS_TOPICS_JSON="${DEVOPS_WORK_DIR}/topics.json"
PING_DEVOPS_MOTD_URL="${PING_DEVOPS_GITHUB_CONTENT}/docs/ping-devops/motd"
PING_DEVOPS_MOTD="${DEVOPS_WORK_DIR}/motd"

################################################################################
# Get Current Kubenetes Info
################################################################################
CURRENT_K8S_CONTEXT="$(kubectl config current-context 2> /dev/null)"
CURRENT_K8S_NAMESPACE="$(kubectl config view --minify --output 'jsonpath={..namespace}' 2> /dev/null)"

################################################################################
# Check for a .pingidentity directory with propertyfile
################################################################################
test -d "${DOT_PINGIDENTITY}" || mkdir -p "${DOT_PINGIDENTITY}"

################################################################################
# Source devops file
################################################################################
test -f "${DEVOPS_FILE}" && source "${DEVOPS_FILE}"

# Temporary directories used to run generate-profile and download product
PROFILE_DIR=""
PROD_DIR=""
TMP_DIR="$(mktemp -d)"

################################################################################
# cleanup - Ensures that we cleanup any temporary directories we create upon exit
################################################################################
function cleanup {      
  rm -rf "$PROFILE_DIR"   
  rm -rf "$PROD_DIR"
  rm -rf "$TMP_DIR"
}

trap cleanup EXIT

################################################################################
# Terminal codes for echoing of RED or GREEN colors, and back to NORMAL
################################################################################
RED='\033[0;31m'
GREEN='\033[0;32m'
NORMAL='\033[0m'
BOLD='\033[1m'

################################################################################
# echo_red - Echo message in red color
################################################################################
echo_red()
{
    echo -e "${RED}$*${NORMAL}"
}

################################################################################
# echo_green - Echo message in green color
################################################################################
echo_green()
{
    echo -e "${GREEN}$*${NORMAL}"
}

################################################################################
# echo_error (message) - Echo's an Error: message
################################################################################
echo_error()
{
    if test  ! -z "$*"; then
      echo "-------------------------------------------------------------------------"
	    echo_red "Error: ${1}"
      echo "-------------------------------------------------------------------------"
    fi
}

function run_command()
{
  CMD="${1}"
  CMD_OUTPUT="${2}"
  echo "-------------------------------------------------------------------------"
  echo -e "Command: ${BOLD}$CMD $(test ! -z "${CMD_OUTPUT}" && echo "> ${CMD_OUTPUT}")${NORMAL}"
  echo "-------------------------------------------------------------------------"
  
  test -z "${CMD_OUTPUT}" && $CMD
  test ! -z "${CMD_OUTPUT}" && $CMD > ${CMD_OUTPUT}
}


################################################################################
# check_devops_file - Verify that the devops_file is found
################################################################################
function check_devops_file()
{
  test ! -f ${DEVOPS_FILE} \
    && echo_red "No ping-devops config found.  Please run:\n" \
    && echo "  ping-devops config" \
    && exit
}

################################################################################
# check_variables - Verify that certain variables are set
################################################################################
function check_variables()
{
  for _var in ${*}; do
    test -z $(get_value ${_var}) \
      && echo_red "Variable is not set: ${_var}" \
      && _var_check_fails=true
  done

  test ${_var_check_fails} \
    && echo -e "\nTo get more information on these variables:" \
    && echo_green "  ping-devops topic devops-variables" \
    && echo -e "\nSet this/these in your config with:" \
    && echo_green "  ping-devops config" \
    && echo "" \
    && exit
}


################################################################################
USAGE_HEADER="${GREEN}################################################################################
#  Ping Identity DevOps (version $VERSION)"

################################################################################
USAGE_FOOTER="${GREEN}Further help:${NORMAL}
  https://github.com/pingidentity/ping-devops"


################################################################################
# usage - Print any message sent as an error and then the usage information
################################################################################
function usage()
{
  echo_error "$*"

  echo -e "$USAGE_HEADER"

  echo -e "#
#  Documentation: https://pingidentity-devops.gitbook.io/devops/
#   GitHub Repos: https://github.com/topics/ping-devops
################################################################################${NORMAL}

${GREEN}General Usage:${NORMAL}
  ping-devops config                            # Configure Ping DevOps
  ping-devops info [-v]                         # Print Config Information
  ping-devops version                           # Version Details and Check
  ping-devops topic [ {topic-name} ]            # Short Help Topics

${GREEN}Generate Kubernetes/Kustomize Resource:${NORMAL}
  ping-devops generate devops-secret                    # Ping DevOps secret
  ping-devops generate tls-secret {domain}              # TLS Cert/Key (i.e. example.com)
  ping-devops generate ssh-id-secret {ssh id_rsa file}  # SSH ID Key (i.e. ~/.ssh/id_rsa)
  ping-devops generate license-secret {license file}    # License file (i.e. pingdirectory.lic)
  ping-devops generate kustomization.yaml               # Skeleton kustomization.yaml

${GREEN}Running Docker/Kubernetes Evironments:${NORMAL}
  ping-devops docker     [info|start|stop|rm|clean]
  ping-devops kubernetes [info|start|rm|clean]  
"

  echo -e "$USAGE_FOOTER"
  exit
}

################################################################################
# usage_command - print usage info for a specific command
################################################################################
function usage_command()
{
  _usageCmd="${1}"
  shift

  echo_error "$*"

  echo -e "$USAGE_HEADER
################################################################################${NORMAL}
"

  case "${_usageCmd}" in
    docker)
      echo -e "${GREEN}Running Docker Getting Started Containers:${NORMAL}
  ping-devops docker info                      # Lists all available use-cases/products
  ping-devops docker info  {product}           # Information on user-case/product
  ping-devops docker start {product}           # Starts services  (i.e. docker-compose up)
  ping-devops docker stop  {product}           # Stops services   (i.e. docker-compose stop)
  ping-devops docker rm    {product}           # Removes services (i.e. docker-compose down)
  ping-devops docker clean                     # Cleans all ping_devops docker services"
      ;;
    kubernetes)
      echo -e "${GREEN}Running Kubernetes Getting Started Containers:${NORMAL}
  ping-devops kubernetes info                  # Lists all available use-cases/products
  ping-devops kubernetes info  {product}       # Information on user-case/product
  ping-devops kubernetes start {product}       # Starts services  (i.e. kubectl create)
  ping-devops kubernetes rm    {product}       # Removes services (i.e. kubectl delete)
  ping-devops kubernetes clean                 # Removes all ping_devops kubernetes resources"
      ;;
    *) usage
      ;;
  esac

  echo ""
  exit
}

################################################################################
# check_for_tool (tool_name)
#
# Using which command, validate that the tool_name is found
################################################################################
check_for_tool()
{
  _tool="${1}"
  which ${_tool} >/dev/null

  test $? -eq 1 && usage "${_tool} tool not found, please install"
}

################################################################################
# get_value (variable)
#
# Get the value of a vaiable, preserving the spaces
################################################################################
get_value ()
{
  if test ! -z "${1}"; then
    IFS="%%"
    eval printf '%s' "\${${1}}"
    unset IFS
  fi
}

################################################################################
# get_value (variable)
#
# Get the value of a vaiable, preserving the spaces
################################################################################
find_setup_arg_value()
{
  _valToFind="${1}"
  _findFile="${2}"
  _defaultVal="${3}"
  
  _valFound=$(grep -e "$_valToFind" ${_findFile} | sed "s/.*$_valToFind \(.*\) .*\\\\$/\1/g")

  test -z "${_valFound}" && _valFound="${_defaultVal}"

  echo "${_valFound}"
}

################################################################################
# add_bash_aliases ()
#
# Ensure that the bash_alias file is a part of .bash_profile
################################################################################
add_bash_aliases()
{


    PING_DEVOPS_BASH_PROFILE="/usr/local/etc/bash_profile.ping-devops"
    BASH_PROFILE="${HOME}/.bash_profile"

    # Touch the .bash_profile incase it's not setup yet
    touch "${BASH_PROFILE}"

    grep "${PING_DEVOPS_BASH_PROFILE}" "${BASH_PROFILE}" > /dev/null

    if test "${?}" == "1"; then
        echo "
################################################################################
#                         Ping Identity DevOps Alias Files
################################################################################

Let's add helper alias' and functions to your shell.  
We are assuming you use bash and will add these to your ${BASH_PROFILE}
"

        echo -n "  OK if we add a 'source ${PING_DEVOPS_BASH_PROFILE}' command to your ${BASH_PROFILE} (y/n) [y] ? "
        read answer

        if [ "${answer}" == "" ] || [ "${answer}" == "Y" ] || [ "${answer}" == "y" ]; then
            echo "
# Ping Identity DevOps Aliases - Added with 'ping-devops config' on `date`
test -f '${PING_DEVOPS_BASH_PROFILE}' && source '${PING_DEVOPS_BASH_PROFILE}'" >> "${BASH_PROFILE}"
        fi
    fi

    grep "sourcePingIdentityFiles" "${BASH_PROFILE}" >/dev/null

    if test "$?" = "1"; then
        echo -n "  OK if we add a 'sourcePingIdentityFiles' command to your ${BASH_PROFILE} (y/n) [y] ? "
        read answer
        if [ "${answer}" == "" ] || [ "${answer}" == "Y" ] || [ "${answer}" == "y" ]; then
            echo "
# Source PingIdentity Files Alias - Added with 'ping-devops config' on `date`
sourcePingIdentityFiles" >> "${BASH_PROFILE}"
        fi
    fi
}

################################################################################
# get_custom_variables ()
#
# Obtain a list of custom variablees
################################################################################
function get_custom_variables()
{
    grep -v "^#" ${DEVOPS_FILE} | \
    while read _line
    do
        test -z "${_line}" && continue
        _name="${_line%%=*}"
        _val="${_line#*=}"

        echo $PING_DEVOPS_STANDARD_VARIABLES | grep ${_name} >/dev/null
        _grepRC=$?
        
        if test ${_grepRC} -ne 0; then
            echo "${_name}"
        fi
    done
}

################################################################################
# devops_add_config (file, variable, default, prompt)
#
# Add a config variale to the devops file, using the prompt sent, and defaulting
# if no value is provided.
################################################################################
function devops_add_config()
{
  PROPS_FILE="${1}" && shift
  VAR_TO_SET="${1}" && shift
  VAR_DEFAULT="${1}" && shift
  VAR_PROMPT="${*}"

  CURRENT_VALUE=$(get_value ${VAR_TO_SET})
  test -z "${CURRENT_VALUE}" && CURRENT_VALUE="${VAR_DEFAULT}"

  echo "${VAR_PROMPT}"
  echo -ne "    [${GREEN}${CURRENT_VALUE}${NORMAL}] ? "
  #echo -ne "${VAR_PROMPT} [${GREEN}${CURRENT_VALUE}${NORMAL}] ? "
  read answer
  echo ""
  if test ! -z "${answer}"; then
    if test "${answer}" = "-"; then
      if test -z "${VAR_TO_SET}"; then
        echo -n "" >> ${PROPS_FILE}
      else
        eval "unset \${VAR_TO_SET}"

        # If the variable being uset, is a standard variable, then echo an
        # empty value in the property file, otherwise, lose it from new
        # property file
        echo $PING_DEVOPS_STANDARD_VARIABLES | grep ${VAR_TO_SET} >/dev/null

        test $? -eq 0 && echo "${VAR_TO_SET}=" >> ${PROPS_FILE}
      fi
    else
      if test -z "${VAR_TO_SET}"; then
        echo -n "${answer}" >> ${PROPS_FILE}
      else
        eval "export \${VAR_TO_SET}=${answer}"
        echo "${VAR_TO_SET}=${answer}" >> ${PROPS_FILE}
      fi
    fi
  else
    if test -z "${VAR_TO_SET}"; then
        echo -n "${CURRENT_VALUE}" >> ${PROPS_FILE}
    else
        echo "${VAR_TO_SET}=${CURRENT_VALUE}" >> ${PROPS_FILE}
    fi
  fi
}

################################################################################
################################################################################
function print_variable_setting_instructions()
{
  echo -e "
################################################################################
#  Setting Variables:
#      [enter]     to accept current value
#      [-]         to unset the value 
#      new value   to change value
################################################################################
  "
}

################################################################################
# devops_add_config_customize (file)
#
# Add a config variale to the devops file, using the prompt sent, and defaulting
# if no value is provided.
################################################################################
function devops_add_config_custom()
{
  PROPS_FILE="${1}" && shift
  _custom_variables="${*}"

  test ! -z "${_custom_variables}" && print_variable_setting_instructions

  for _varName in ${_custom_variables}; do
      devops_add_config ${PROPS_FILE} ${_varName}  ""  "Set Custom Variable '${_varName}'"
  done

  echo -e "
################################################################################
#  Add Additional Variables:
#
#      [enter]     to end adding additional variables
#      NAME=VALUE  to add that variable with setting (i.e. VERBOSE=true)
################################################################################
  "
  
  while true
  do
      echo -ne "Enter a new NAME=VALUE [enter to end] : "

      read answer

      test -z "${answer}" && break

      echo "$answer" >> ${PROPS_FILE}
  done


  # CURRENT_VALUE=$(get_value ${VAR_TO_SET})
  # test -z "${CURRENT_VALUE}" && CURRENT_VALUE="${VAR_DEFAULT}"

  # echo "${VAR_PROMPT}"
  # echo -ne "    [${GREEN}${CURRENT_VALUE}${NORMAL}] ? "
  # #echo -ne "${VAR_PROMPT} [${GREEN}${CURRENT_VALUE}${NORMAL}] ? "
  # read answer
  # echo ""
  # if test ! -z "${answer}"; then
  #   if test "${answer}" = "-"; then
  #     if test -z "${VAR_TO_SET}"; then
  #       echo -n "" >> ${PROPS_FILE}
  #     else
  #       eval "unset \${VAR_TO_SET}"
  #       echo "${VAR_TO_SET}=" >> ${PROPS_FILE}
  #     fi
  #   else
  #     if test -z "${VAR_TO_SET}"; then
  #       echo -n "${answer}" >> ${PROPS_FILE}
  #     else
  #       eval "export \${VAR_TO_SET}=${answer}"
  #       echo "${VAR_TO_SET}=${answer}" >> ${PROPS_FILE}
  #     fi
  #   fi
  # else
  #   if test -z "${VAR_TO_SET}"; then
  #       echo -n "${CURRENT_VALUE}" >> ${PROPS_FILE}
  #   else
  #       echo "${VAR_TO_SET}=${CURRENT_VALUE}" >> ${PROPS_FILE}
  #   fi
  # fi
}

################################################################################
# devops_add_comment (file, comment)
#
# Add a comment to the devops file
################################################################################
function devops_add_comment()
{
  _TFILE="${1}" && shift
  _MSG="${@}"

  echo ${_MSG}
  echo ${_MSG} >> ${_TFILE}
}

echo_info_variable()
{
  _varToEcho="${1}"

  printf "  %-30s : %s\n" "${_varToEcho}" "$(get_value ${_varToEcho})"
}

################################################################################
# ping_devops_info ()
#
# Prints all the variables of the ~/.pingidentity/devops file
################################################################################
ping_devops_info()
{
    _show="${1}"

    test "${_show}" != "-v" && PING_IDENTITY_DEVOPS_KEY="*** REDACTED *** (use -v to display)"


    ${CURL} ${PING_DEVOPS_MOTD_URL} \
              --output ${PING_DEVOPS_MOTD} \
              --fail 2>/dev/null

    _curl_result=$?

    if test ${_curl_result} -ne 0; then
        echo "Unable to retrieve latest news." > ${PING_DEVOPS_MOTD}
    fi

    # Get the MOTD
    _jqExpr="\"# Subject: \" + .subject + \"\n#          \" +
                         (.message | join(\"\n#          \")) +
               \"\n\""

    echo "
################################################################################
#     Ping Identity DevOps Information (version $VERSION)
#
#     Latest News from Ping Identity DevOps
#
$(test -f "${PING_DEVOPS_MOTD}" && sed 's/^/#     /' < "${PING_DEVOPS_MOTD}")
#"

echo "################################################################################
#     DevOps variables sourced from ${PRINT_DEVOPS_FILE}
################################################################################
"

    echo_info_variable PING_IDENTITY_DEVOPS_USER
    echo_info_variable PING_IDENTITY_DEVOPS_KEY
    echo ""
    echo_info_variable PING_IDENTITY_DEVOPS_HOME
    echo_info_variable PING_IDENTITY_DEVOPS_REGISTRY
    echo ""
    echo_info_variable PING_IDENTITY_DEVOPS_TAG
    echo ""
    echo_info_variable PING_IDENTITY_ACCEPT_EULA


_listOfCustom_Variables=$(get_custom_variables)

if test ! -z "$_listOfCustom_Variables"; then
  echo "
################################################################################
#     Custom Variables
################################################################################
"

  for _custVar in $_listOfCustom_Variables
  do
      echo_info_variable "${_custVar}"
  done
fi

if test ! -z ${CURRENT_K8S_CONTEXT} && test ! -z ${CURRENT_K8S_NAMESPACE}; then
    echo "
################################################################################
#     Current Kubernetes (k8s) Environment
################################################################################
"
    printf "  %-30s : %s\n" "Current k8s Context" "$(get_value CURRENT_K8S_CONTEXT)"
    printf "  %-30s : %s\n" "Current k8s Namespace" "$(get_value CURRENT_K8S_NAMESPACE)"
fi


echo "
################################################################################
 To change config, run: 
    ping-devops config
"
}

function print_update_information
{
  echo "
to update, you can use:
  macosx : brew upgrade ping-devops
  linux  : curl -L https://bit.ly/ping-devops-install | bash"
}
################################################################################
# ping_devops_version ()
#
# Prints tool version info
################################################################################
ping_devops_version()
{
    # Looks for the URL and pulls out the version.  Example should be:
    #
    #      url "https://github.com/pingidentity/ping-devops/archive/v0.5.0.tar.gz"
    #
    _latest_tool_version=$(${CURL} https://bit.ly/ping-devops-version \
      |  grep -e '^  url ".*"$' \
      |  sed "s/.*archive\/v\(.*\)\.tar.*/\1/")

    _curl_result=$?

    test ${_curl_result} -ne 0 || test -z "${_latest_tool_version}" && _latest_tool_version="UNKNOWN"
    
    if test "${_latest_tool_version}" = "${VERSION}" ||
       test "${_latest_tool_version}" = "UNKNOWN"; then
        _version_msg="${GREEN}${VERSION}${NORMAL} (no update required)"
    else
        _version_msg="${RED}${VERSION}${NORMAL} (updated version ${_latest_tool_version} is available)\n$(print_update_information)"
    fi

    echo -e "ping-devops version ${_version_msg}"
}

################################################################################
# print_topic
#
# topic - topic from pingidentity-devops-getting-started/docs/ping-devops/.
################################################################################
function print_topic()
{
  _topic="${1}"

  # Pull the list of topics from the github api
  ${CURL} ${PING_DEVOPS_TOPICS_JSON_URL} \
              --output ${PING_DEVOPS_TOPICS_JSON} \
              --fail 2>/dev/null

  _curl_result=$?

  if test ${_curl_result} -ne 0; then
      echo "Unable to retrieve list of topics (trying github.com)"
      exit 1
  fi

  if test -z ${_topic}; then
      echo_green "
################################################################################
#          Ping Identity DevOps Topics
################################################################################
"

      # Parses the TOPICS_JSON which comes from github as a json document
      cat "${PING_DEVOPS_TOPICS_JSON}" | jq -r "
          [.[]

          # Map column names to data
          | {
              Topic: .name
          }
          ]

          # lowercase keys
          # (for predictable sorting, optional)
          |  [.[]| with_entries( .key |= ascii_upcase ) ]

          # print headers
          | (.[0] |keys_unsorted | @tsv)

          # print data
            , (.[]|.|map(.) |@tsv)                       # print table

          "  | tr '\t' '|' | column -t -s '|'
          echo ""
  else
      echo_green "
################################################################################
#          Ping Identity DevOps Topic: ${_topic}
################################################################################
"
      # Pull the topic from the topics location
      ${CURL} ${PING_DEVOPS_TOPICS_URL}/${_topic} \
                  --output "${DEVOPS_WORK_DIR}/_${_topic}" \
                  --fail 2>/dev/null

      _curl_result=$?

      if test ${_curl_result} -ne 0; then
          echo "Unable to retrieve topic '${_topic}'."
          echo -e "\nTo get a list of topics:"
          echo_green "  ping-devops topic"
          echo 
          exit 1
      fi

      cat ${DEVOPS_WORK_DIR}/_${_topic}
      echo ""
      echo ""
      echo_green "################################################################################"
  fi
}



################################################################################
################################################################################
function generate_resource()
{
    _secret="${1}"

    test -z "${_secret}" && usage

    case "${_secret}" in
        devops-secret)
            check_variables \
                PING_IDENTITY_DEVOPS_USER \
                PING_IDENTITY_DEVOPS_KEY 
                
            check_for_tool $BASE64
            _devopsUser=$(base64_no_newlines "${PING_IDENTITY_DEVOPS_USER}")
            _devopsKey=$(base64_no_newlines "${PING_IDENTITY_DEVOPS_KEY}")
            echo "
apiVersion: v1
kind: Secret
metadata:
  name: devops-secret
type: Opaque
data:
  PING_IDENTITY_DEVOPS_USER: ${_devopsUser}
  PING_IDENTITY_DEVOPS_KEY: ${_devopsKey}
"
            ;;

        tls-secret)
            _domain="${2}"
            test -z "${_domain}" && usage "Missing tls-secret domain"
            CERTS_DIR=$(mktemp -d)
            cd "${CERTS_DIR}"
            DOMAIN="ping-devops.com"

            check_for_tool $OPENSSL
            check_for_tool $BASE64
            $OPENSSL req -x509 -nodes -newkey rsa:2048 -days 3650 -sha256 \
              -out tls.crt -keyout tls.key \
              -subj "/CN=${DOMAIN}" \
              -reqexts SAN -extensions SAN \
              -config <(cat /etc/ssl/openssl.cnf; printf "[SAN]\nsubjectAltName=DNS:*.${DOMAIN}") > /dev/null 2>&1

            _tlsCRT="$(base64_no_newlines tls.crt)"
            _tlsKEY="$(base64_no_newlines tls.key)"
            echo "
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: tls-secret
data:
  tls.crt: ${_tlsCRT}
  tls.key: ${_tlsKEY}"

            cd - > /dev/null
            rm -rf "${CERTS_DIR}"

            ;;
        ssh-id-secret)
            _idKey="${2}"

            echo "
apiVersion: v1
kind: Secret
metadata:
  name: ssh-id-key-secret
data:
  id_rsa: |
    $(base64_no_newlines ${_idKey})"
            ;;
        license-secret)
            generate_license_secret "${2}"
            ;;

        kustomization|kustomization.yaml)
            cd ${CWD}
            echo "Generating a kustomization.yaml for current directory"
            if test -f ./kustomization.yaml; then
                echo_red "ERROR: kustomization.yaml already exists"
            fi

            cat <<EOK >kustomization.yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
EOK
            for f in */; do
              echo "- ${f%/}" >> kustomization.yaml
            done

            for f in *.yaml; do
              test "${f}" != "kustomization.yaml" && echo "- ${f%}" >> kustomization.yaml
            done
            ;;
        *)
            usage "generate" "Unknown resource to generate '${_secret}'"
            ;;
    esac
} 

################################################################################
# generate_license_secret (name of product or license file)
#
# Generates a license secret for the passed license file or name of product
#  - license_file or product_name
################################################################################
function generate_license_secret()
{
  _licenseArg="${1}"

  if test -f ${_licenseArg}; then
    _licenseSecret=$(base64_no_newlines ${_licenseArg})
  else

    case "${_licenseArg}" in
      pingaccess|pingcentral|pingdatametrics|pingdatasync|pingdatagovernance|pingdatagovernancepap|pingdirectory|pingdirectoryproxy|pingfederate)
         
        check_for_tool $DOCKER

        check_variables \
            PING_IDENTITY_DEVOPS_USER \
            PING_IDENTITY_DEVOPS_KEY 

        $DOCKER run --rm -v /tmp:/tmp ${PING_IDENTITY_DEVOPS_REGISTRY}/pingdownloader \
          --product ${_licenseArg} \
          --license \
          --devops-user "${PING_IDENTITY_DEVOPS_USER}" \
          --devops-key "${PING_IDENTITY_DEVOPS_KEY}" \
          --devops-app "pingdevops-${_licenseArg}" | grep "^\#"
        _dockerRunResult=$?

        test $_dockerRunResult -ne 0 && usage "Unable to pull eval license (result=$_dockerRunResult)" 
      
        _licenseSecret=$(base64_no_newlines /tmp/product.lic)

        rm /tmp/product.lic
        ;;
      *)
        usage "License File '${_licenseArg}' not found"
        ;;
    esac
  fi
            echo "
apiVersion: v1
kind: Secret
metadata:
  name: license-secret
data:
  license: |
    ${_licenseSecret}"

}

################################################################################
# generate_profile (arguments)
#
# Generates a profile for the provided arguments:
#  - product
#  - current-install {directory}     (optional)
#  - generated-profile {directory}   (optional)
#  - variables-file {file}           (optional)
################################################################################
function generate_profile()
{
    _product="${1}"
    shift
    while ! test -z "${1}" ; do
        case "${1}" in
            --current-install)
                shift
                _currentInstall="${1}"
                ;;
            --generated-profile)
                shift
                _generatedProfile="${1}"
                ;;
            --variables-file)
                shift
                _variablesFile="${1}"
                usage "--variables-file option not implemented yet"
                ;;
            *)
                usage "Unknown generate-profile option '${1}'"
                ;;
        esac
        shift
    done

    test -z "${_generatedProfile}" && _generatedProfile="${CWD}/${_product}"
    
    test -d "${_generatedProfile}" && 
        usage "Generated Profile directory '${_generatedProfile}' not empty" 

    echo "
################################################################################
#   Ping DevOps Server Profile Generation
################################################################################
"

    PROFILE_DIR=`mktemp -d`
    if [[ ! "$PROFILE_DIR" || ! -d "$PROFILE_DIR" ]]; then
      usage "Could not create temp dir using mktemp."
    fi

    PROD_DIR=`mktemp -d`
    if [[ ! "$PROD_DIR" || ! -d "$PROD_DIR" ]]; then
      usage "Could not create raw dir using mktemp." 
    fi

    if test -z "${_currentInstall}" ; then
      echo "No current install provided."
      echo "  ==> Using 'docker run ${PING_IDENTITY_DEVOPS_REGISTRY}/pingdownloader -p ${_product}"
      echo "  ==> to pull down the latest bits for ${_product}"

      check_for_tool $DOCKER
      $DOCKER run --rm -v /tmp:/tmp ${PING_IDENTITY_DEVOPS_REGISTRY}/pingdownloader \
          --product ${_product} \
          --devops-user "${PING_IDENTITY_DEVOPS_USER}" \
          --devops-key "${PING_IDENTITY_DEVOPS_KEY}" \
          --devops-app "ping-devops-generate-profile-${_product}"
      _dockerRunResult=$?

      test $_dockerRunResult -ne 0 && usage "Unable to download product via docker (result=$_dockerRunResult)" 
      
      unzip -q /tmp/product.zip -d ${PROD_DIR}
      
      _currentInstall="${PROD_DIR}/PingDirectory"

      rm /tmp/product.zip
    fi
    
    test ! -d "${_currentInstall}" && 
        usage "Current Install '${_currentInstall}' not found" 

    case "${_product}" in
        pingdirectory)
            generate_server_profile_pingdirectory "${_src}"
            ;;
        pingaccess|pingdatagovernance|pingdatasync|pingfederate)
            usage "Not implemented for product '${_product}'."
            ;;
        *)
            usage "Unknown product '${_product}'."
            ;;
    esac
} 

################################################################################
# generate_server_profile_pingdirectory ()
#
# Generates a server profile for Ping Directory
################################################################################
generate_server_profile_pingdirectory()
{
    _serverRoot="${_currentInstall}"

    # Validate that we have an actual PingDirectory install with the manage-profile
    # binary
    test ! -x ${_serverRoot}/bin/manage-profile && \
        usage "Unable to find manage-profile in product."

    cd ${PROFILE_DIR}

    # Create a directory to generate a profile into
    mkdir pd.profile
    ${_serverRoot}/bin/manage-profile generate-profile --profileRoot pd.profile >/dev/null


    # Create a secrets directory where we will place some password files.
    mkdir secrets
    echo "What initial passwords would you like to set in your generated profile for the:"
    echo "   ROOT_USER      - Password used for your root dn (i.e cn=administrator)"
    echo "   ADMIN_USER     - Password used with your administrative framework (i.e. dsreplication)"
    echo "   ENCRYPTION     - Password used to encrypt your encryption settings"
    echo ""
    echo "These will be placed into seperate password files and referenced in an env_vars file at the"
    echo "top of your generated profile.  For better security, these should be placed into a secret"
    echo "or vault, mounted into your container and refrenced by your env_vars location."
    echo ""

    _randomPassword="$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9@%^_+?~' | fold -w 12 | head -c 12)"
    devops_add_config "secrets/root-user-pwd"  "" "$_randomPassword" "Initial ROOT_USER_PASSWORD? "
    devops_add_config "secrets/admin-user-pwd" "" "$_randomPassword" "Initial ADMIN_USER_PASSWORD? "
    devops_add_config "secrets/encryption-pwd" "" "$_randomPassword" "Initial ENCRYPTION_PASSWORD? "

    #
    # env_vars File
    #
    # Pull several arguments in the generated setup-arguments.txt file create the proper
    # environment variables
    _setupArgs="pd.profile/setup-arguments.txt"
    echo "
# Generated by 
#    ping-devops generate-profile pingdirectory
#
# on $(date)
#
# The following environment variables are used by the
# Ping Identity Ping Directory image.
#
ROOT_USER_PASSWORD_FILE=\${STAGING_DIR}/secrets/root-user-pwd
ADMIN_USER_PASSWORD_FILE=\${STAGING_DIR}/secrets/admin-user-pwd
ENCRYPTION_PASSWORD_FILE=\${STAGING_DIR}/secrets/encryption-pwd

ROOT_USER_DN=$(find_setup_arg_value  "--rootUserDN"  ${_setupArgs}  "cn=administrator")
USER_BASE_DN=$(find_setup_arg_value  "--baseDN"      ${_setupArgs}  "dc=example,dc=com")
LDAP_PORT=$(find_setup_arg_value     "--ldapPort"    ${_setupArgs}  "389")
LDAPS_PORT=$(find_setup_arg_value    "--ldapsPort"   ${_setupArgs}  "636")
HTTPS_PORT=$(find_setup_arg_value    "--httpsPort"   ${_setupArgs}  "443")
MAX_HEAP_SIZE=$(find_setup_arg_value "--maxHeapSize" ${_setupArgs}  "384m")
LOCATION=$(find_setup_arg_value      "--location"    ${_setupArgs}  "home")

" > env_vars

    mv pd.profile/setup-arguments.txt setup-arguments.txt-FROM-SOURCE

    #
    # docker-compose.yaml File
    #
    echo "
# Ping Identity ping-devops generate-profile
#
# Generated on $(date)
#
version: \"3.1\"
# This docker-compose.yaml was generated by 'ping-devops' tool on $(date)

services:
  pingdirectory:
    image: \${PING_IDENTITY_DEVOPS_REGISTRY}/pingdirectory:\${PING_IDENTITY_DEVOPS_TAG}
    container_name: pingdirectory
    environment:
      #- SERVER_PROFILE_URL=...url of your git repo...and comment out the volumes /opt/in...
      #- SERVER_PROFILE_PATH=...path in your git repo...
      - PING_IDENTITY_ACCEPT_EULA=YES
      - ORCHESTRATION_TYPE=compose
      - COMPOSE_SERVICE_NAME=pingdirectory_service
    env_file:
      # Configuration file created when setup.sh (Getting-started project root directory) is first run to source
      # devops user/key details for evaluation licenses and for docker image/git tags
      - ${PRINT_DEVOPS_FILE}
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out)
    volumes:
    #   - \${HOME}/projects/devops/volumes/pingdirectory_service:/opt/out
       - ${_generatedProfile}:/opt/in
    networks:
      - pingnet
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 1389-1399:389
      - 1636-1646:636
      - 1443-1453:443
      
  pingdataconsole:
    image: \${PING_IDENTITY_DEVOPS_REGISTRY}/pingdataconsole:\${PING_IDENTITY_DEVOPS_TAG}
    container_name: pingdataconsole
    ports:
      - 8443:8443
    networks: 
      - pingnet
                    
networks:
    pingnet:

" > docker-compose.yaml

    #
    # README.md File
    #
    echo "
# Ping Directory Server Profile

Generated by \`ping-devops\` tool on $(date)
* Product: ${_product}
* Current Install: ${_currentInstall}
* Generated Profile: ${_generatedProfile}

# Testing with docker-compose
## Starting up image

    cd ${_generatedProfile}
    docker-compose up -d

## Watching PingDirectory Logs

    docker logs -f ${_product}

## Running PingDataconsole

https://localhost:8443
  Username: administrator
  Password: $(cat ${PROFILE_DIR}/secrets/root-user-pwd)

" > README.md

    #
    # motd File
    #
    echo "
This server profile was generated by 'ping-devops' tool on $(date)

Source Product
==============
$(${_serverRoot}/bin/status -V)
" > motd

    mkdir -p "${_generatedProfile}"

    mv * ${_generatedProfile}/.

    echo
    echo "######################## README.md ############################"
    
    which mdcat >/dev/null
    _whichResult=$?

    if test $_whichResult -eq 0; then
      mdcat ${_generatedProfile}/README.md
    else
      cat ${_generatedProfile}/README.md
    fi
}

# ################################################################################
# ################################################################################
# generate_server_profile_pingfederate()
# {
#     _serverRoot="${_currentInstall}"

#     # Validate that we have an actual Pingfederate install with a bin/run.sh
#     # script
#     test ! -x ${_serverRoot}/bin/run.sh && \
#         usage "Unable to find 'bin/run.sh' in '${_serverRoot}'."

#     cd ${_currentInstall}

#     SRC_FILES=/tmp/pf.sourcefiles
#     find . -print > ${SRC_FILES}

#     cd ${PROFILE_DIR}
#     _secretsDir="${PROFILE_DIR}/secrets"   && mkdir -p ${_secretsDir}
#     _profileDir="${PROFILE_DIR}/pf.profile"   && mkdir -p ${_profileDir}
#     _instanceDir="${_profileDir}/instance" && mkdir -p ${_instanceDir}


#     # 
#     # For every file in the current installation, look for any files that:
#     #  - we should ignore (i.e. ./log*, ./lib*, ...)
#     #  - if there is pid file, simply provide a message alerting this fact
#     #  - JWK file.  provide a message and copy it to our secrets folder for now.
#     #  - everything else, see if there is a difference, or if it is a new file and copy it.
#     while read f; do
#       case $f in
#         # IGNORE THESE FILES   
#         (./connection_export_examples*|./legal*|./lib*|./log*|./modules*|./sbin/*|./server/default/tmp*|./server/default/data/archive*|./server/default/data/instance*|./server/default/lib*|./sdk*|./upgrade*|./work*) 
#           ;;
#         # Provide a message that the server may be running  
#         (*.pid)
#           echo "Seems to be running - $f"
#           ;;
#         # Place this file in the secrets directory
#         (*.jwk)
#           cp ${_currentInstall}/$f ${_secretsDir}/$(basename $f)
#           echo "Got a .jwk!!! - $f"
#               #  mkdir -p ${_instanceDir}/$(dirname $f) 
#               #  cp ${_currentInstall}/$f ${_instanceDir}/$f 
#           ;;
#         # Everything else, 
#         # if directory, just ignore
#         # If a file isn't found in PRODUCT dir, we need to make the directory and copy.
#         # test to see if difference and copy if new or different.
#         *)
#           test -d ${_currentInstall}/$f && continue
#           test ! -f /ping/pingfederate-10.0.0/pingfederate/$f && mkdir -p ${_instanceDir}/$(dirname $f) && cp ${_currentInstall}/$f ${_instanceDir}/$f && continue

#           diff ${_currentInstall}/$f /ping/pingfederate-10.0.0/pingfederate/$f >/dev/null 2>/dev/null
#           _diffResult=$?
          
#           case $_diffResult in
#             0)
#                echo "NO DIFFERENCE - $f" 
#                ;;
#             1|2)
#                mkdir -p ${_instanceDir}/$(dirname $f) 
#                cp ${_currentInstall}/$f ${_instanceDir}/$f 
#                ;;
#           esac
#           ;;
#       esac
#     done <${SRC_FILES}

#     tree ${PROFILE_DIR}

#     echo "

# This server profile was generated by 'ping-devops' tool.

# Source Product
# ==============
# TODO GET PF VERSION INFO
# " > motd

#     mkdir -p "${_generatedProfile}"

#     mv * ${_generatedProfile}/.
# }


# ################################################################################
# ################################################################################
# generate_server_profile_pingaccess()
# {
#     _serverRoot="${_currentInstall}"

#     test ! -x ${_serverRoot}/??? && \
#         usage "Unable to find ??? in product."

#     cd ${PROFILE_DIR}

#     mkdir instance
    
#     echo "

# This server profile was generated by 'ping-devops' tool.

# Source Product
# ==============
# TODO GET PA VERSION INFO
# " > motd

#     mkdir -p "${_generatedProfile}"

#     mv * ${_generatedProfile}/.
# }

################################################################################
# get_ping_devops_json
#
################################################################################
function get_ping_devops_json ()
{
    # Get the ping-devops.json file
    _curl_result=0
    
    ${CURL} -H "User-Agent: ping-devops" ${PING_DEVOPS_URL} \
              --output ${PING_DEVOPS_JSON} \
              --fail 2>/dev/null

    _curl_result=$?

    if test ${_curl_result} -ne 0; then
        usage "Unable to get ping-devops.json (trying github.com)"
    fi

    _json_version=$(cat ${PING_DEVOPS_JSON} | jq -r '.minVersion')

    if test "${_json_version}" != "${VERSION}" &&
       test "$( echo -e "${_json_version}\\n${VERSION}" | sort -V | head -2 | tail -1)" = ${_json_version}
    then
      echo "ping-devops update required"
      echo -e "           current version ${RED}${VERSION}${NORMAL}"
      echo -e "  minimum required version ${GREEN}${_json_version}${NORMAL}"
      print_update_information
      exit
    fi
}

################################################################################
# print_orchestration_usecase
#
# orchestration - docker or kubernetes
# product       - product or usecase name
# file          - file with comments
################################################################################
function print_orchestration_usecase()
{
  _orchestation="${1}"
  _product_usecase="${2}"
  _usecase_file="${3}"

  if test -z ${_product_usecase}; then
      echo_green "
################################################################################
#          Available ping-devops ${_orchestation} usecase/products
################################################################################
"

      cat "${PING_DEVOPS_JSON}" | jq -r "
          [.${_orchestation}.usecases | .[]

          # Map column names to data
          | {
              Name: .name,
              Description: .description
          }
          ]

          # lowercase keys
          # (for predictable sorting, optional)
          |  [.[]| with_entries( .key |= ascii_upcase ) ]

          # print headers
          | (.[0] |keys_unsorted | @tsv)

          # print data
            , (.[]|.|map(.) |@tsv)                       # print table

          "  | tr '\t' '|' | column -t -s '|'
  else
      grep "^#-" "${_usecase_file}"
  fi

  echo ""
}


################################################################################
# orchestration_command
#
# Perform a kubernetes command
#  - orchestrator (docker, kubernetes)
#  - command      (info, start, stop, rm, clean)
#  - product      (i.e. pingdirectory, pingfederate)
################################################################################
function orchestration_command()
{
    _orchestrator="${1}"
    shift
    _cmd="${1}"
    shift
    _product="${1}"

    check_devops_file
    check_for_tool $JQ

    case "${_orchestrator}" in
        docker)
            check_for_tool $DOCKER
            check_for_tool $DOCKER_COMPOSE

            check_variables \
                PING_IDENTITY_ACCEPT_EULA \
                PING_IDENTITY_DEVOPS_USER \
                PING_IDENTITY_DEVOPS_KEY \
                PING_IDENTITY_DEVOPS_REGISTRY \
                PING_IDENTITY_DEVOPS_TAG

            _orch_file="docker-compose.yaml"
            ;;
        kubernetes)
            check_for_tool $KUBECTL
            check_for_tool $KUSTOMIZE
            check_for_tool $ENVSUBST
            check_for_tool $KUBECTX
            check_for_tool $KUBENS

            check_variables \
                PING_IDENTITY_ACCEPT_EULA \
                PING_IDENTITY_DEVOPS_USER \
                PING_IDENTITY_DEVOPS_KEY \
                PING_IDENTITY_DEVOPS_REGISTRY \
                PING_IDENTITY_DEVOPS_TAG

            _orch_file="kustomization.yaml"
            ;;
        *) 
            usage "Unknown orchestration '${_orchestrator}'.";;
    esac


    # Get the .ping-devops.json file
    get_ping_devops_json
    
    _docker_compose_project_name="ping_devops"

    #
    # If a product is passed, then we will parse the .ping-devops.json
    # file to get the:
    #   - BaseURL for information
    #   - BaseURL for kustomize URL
    #   - usecase path
    if test ! -z "${_product}"; then
        mkdir -p ${DEVOPS_WORK_DIR}/${_product}
        _info_base_url=$(cat "${PING_DEVOPS_JSON}" | jq -r ".baseURL")
        _kust_base_url=$(cat "${PING_DEVOPS_JSON}" | jq -r ".baseKustomizeURL")
        _usecase_path=$(cat "${PING_DEVOPS_JSON}" | jq -r ".${_orchestrator}.usecases[] | select ( [.name] == [\"${_product}\"]) | .path")
        
        #
        # If we have a usecase path found, then we will create the URLs
        # to pull the information files as well as creating the options for
        # docker-compose
        if test ! -z "${_usecase_path}"; then
          _info_url="${_info_base_url}/${_usecase_path}/${_orch_file}"
          _kust_url="${_kust_base_url}/${_usecase_path}"

          _orch_file="${DEVOPS_WORK_DIR}/${_product}/${_orch_file}"
          _docker_compose_options="--file ${_orch_file} --project-name ${_docker_compose_project_name}"


          # Get the product orchestration file
          ${CURL} ${_info_url} \
                --output ${_orch_file} \
                --fail 2>/dev/null >/dev/null

          _curl_result=$?
        else
          _curl_result=1
        fi
        
        # If we can't find a kustomization.yaml, then we will change the command to info
        # and provide a message that we can't download info for the product.
        if test ${_curl_result} -ne 0; then
            rm -rf ${DEVOPS_WORK_DIR}/${_product}
            echo_red "Unable to download info for '${_product}'"
            test ! -z "${_info_url}" && echo_red "  URL: ${_info_url}"
            _cmd="info"
            _product=""
        fi
    else
        case "${_cmd}" in
            start|stop|rm)
                echo_red "Product required to complete command '${_cmd}'"
                _cmd="info"
                ;;
            *)  ;;
        esac
    fi

    case "${_cmd}" in
        info)
            print_orchestration_usecase "${_orchestrator}" "${_product}" "${_orch_file}"
            ;;
        start)
            case "${_orchestrator}" in
                docker)
                    run_command "${DOCKER_COMPOSE} ${_docker_compose_options} pull"
                    run_command "${DOCKER_COMPOSE} ${_docker_compose_options} up --detach"

                    echo ""
                    grep "^#-" "${_orch_file}"
                    echo "#  Additional Docker Commands
#
#             List Containers - docker container ls
#        Watch Container Logs - docker container logs -f  {container-id}
#   Exec Shell Into Container - docker container exec -it {container-id} /bin/sh
################################################################################
"
                    ;;
                kubernetes)
                    pushd ${TMP_DIR} > /dev/null
                    
                    run_command "ping-devops generate devops-secret" "devops-secret.yaml"
                    run_command "$KUBECTL apply -f devops-secret.yaml"
                    run_command "ping-devops generate tls-secret ${PING_IDENTITY_DEVOPS_DNS_ZONE}" "tls-secret.yaml"
                    run_command "$KUBECTL apply -f tls-secret.yaml"
                    run_command "$KUSTOMIZE build ${_kust_url}" "kustomize_output.yaml"
                    mv kustomize_output.yaml before_envsubst.yaml
                    cat before_envsubst.yaml | envsubst > kustomize_output.yaml
                    #$KUSTOMIZE build "${_kust_url}" | envsubst > kustomize_output.yaml
                    run_command "$KUBECTL create -f kustomize_output.yaml"

                    popd > /dev/null

                    echo ""
                    grep "^#-" "${_orch_file}"
                    echo -e "#  Starting kubernetes deployment of '${_product}'
#  
#     Kustomization URL: ${_kust_url}
#    Kubernetes Context: ${GREEN}${CURRENT_K8S_CONTEXT}${NORMAL}
#  Kubernetes Namespace: ${GREEN}${CURRENT_K8S_NAMESPACE}${NORMAL}
# 
#  Additional kubectl Commands
# 
#             List Containers - kubectl get all
#    Watch Container/Pod Logs - kubectl logs {pod-name} -f
#   Exec Shell Into Container - kubectl exec -it {pod-name} -- /bin/sh
#  Port Forward - HTTP Access - kubectl port-forward service/{service-name} {port}
################################################################################
"

                    ;;
            esac


            ;;
        stop|rm)
            case "${_orchestrator}" in
                docker)
                    test ${_cmd} = "stop" && run_command "${DOCKER_COMPOSE} ${_docker_compose_options} stop"
                    test ${_cmd} = "rm"   && run_command "${DOCKER_COMPOSE} ${_docker_compose_options} down"
                    ;;
                kubernetes)
                    pushd ${TMP_DIR} > /dev/null
                    
                    run_command "$KUSTOMIZE build ${_kust_url}" "kustomize_output.yaml"
                    mv kustomize_output.yaml before_envsubst.yaml
                    cat before_envsubst.yaml | envsubst > kustomize_output.yaml
                    #$KUSTOMIZE build "${_kust_url}" | envsubst > kustomize_output.yaml
                    run_command "$KUBECTL delete -f kustomize_output.yaml"

                    popd > /dev/null
                    ;;
            esac
            ;;
        clean)
            case "${_orchestrator}" in
                docker)
                    echo ""
                    echo "You are about to clean all the ping_devops images below..."
                    echo ""
                    docker container ls -a --filter name=${_docker_compose_project_name}_*
                    echo ""
                    echo_red "IMPORTANT: This is destructive of all content in these running containers.
        "

                    echo -n "Are you SURE you want to clean these ping_devops images (y/n) [n] ? "
                    read answer

                    if [ "${answer}" != "Y" ] && [ "${answer}" != "y" ]; then
                        echo_error "Clean Aborted!"
                        exit
                    fi

                    for _prod_option in $(ls -d ${DEVOPS_WORK_DIR}/* 2>/dev/null); do

                        _docker_compose_dir="${DEVOPS_WORK_DIR}/$(basename ${_prod_option} )"
                        _docker_compose_options="--file ${_docker_compose_dir}/docker-compose.yaml --project-name ${_docker_compose_project_name}"

                        echo "Cleaning up ${_prod_option}"
                        run_command "${DOCKER_COMPOSE} ${_docker_compose_options} down "

                        rm -rf "${_docker_compose_dir}"
                    done
                    run_command "${DOCKER} container prune -f"
                    ;;
                kubernetes)
                    echo ""
                    echo "You are about to clean all the kubernetes resources below..."
                    echo ""
                    echo -e "################################################################################"
                    echo -e "#    Kubernetes Context: ${GREEN}${CURRENT_K8S_CONTEXT}${NORMAL}"
                    echo -e "#  Kubernetes Namespace: ${GREEN}${CURRENT_K8S_NAMESPACE}${NORMAL}"
                    echo -e "################################################################################"
                    kubectl get all
                    echo ""
                    echo_red "IMPORTANT: This is destructive of all content in these running containers.
        "

                    echo -n "Are you SURE you want to clean these kubernetes resources (y/n) [n] ? "
                    read answer

                    if [ "${answer}" != "Y" ] && [ "${answer}" != "y" ]; then
                        echo_error "Clean Aborted!"
                        exit
                    else
                        run_command "kubectl delete pods,statefulsets,deployments,services -n ${_namespace} --grace-period=0 --force --all"
                    fi

                    echo ""
                    echo -e "################################################################################"
                    echo -e "#    All pods, statefulsets, deployments and services have been deleted."
                    echo -e "#    To perform a deep clean on all other kubernetes in your workspace use"
                    echo -e "#    following alias:"
                    echo -e "# "
                    echo -e "#    knuke"
                    echo -e "################################################################################"
                    
                    ;;
            esac
            ;;
        *)
            usage_command "${_orchestrator}" "Unknown ${_orchestrator} command"
            ;;
    esac
    
}

################################################################################
################################################################################
function devops_config()
{

    ################################################################################
    # Get all the custom variables from the devops file before we backup
    ################################################################################
    _custom_variables=$(get_custom_variables)

    ################################################################################
    # Check for existance of the devops file and backup to .prev
    ################################################################################
    if test -f "${DEVOPS_FILE}"; then
        mv "${DEVOPS_FILE}" "${DEVOPS_FILE}".prev

        # If the config is broken (i.e. ctrl-c) then restore the previous file
        trap '
            echo ""
            echo "restoring: ${DEVOPS_FILE}"
            mv "${DEVOPS_FILE}".prev "${DEVOPS_FILE}"
            exit
        ' HUP INT PIPE TERM 
    fi

    echo "

################################################################################
#
#                     Welcome to Ping Identity DevOps!
#
#  We will run through a few config items to make your experiance as easy as 
#  possible.  These include:
#  
#    - Setting up your default '${PRINT_DEVOPS_FILE}' settings
#    - Adding bash_profile.ping-devops to your .bash_profile, if neeeded
#"

    echo "################################################################################
#              Ping Identity DevOps Docker Variables
################################################################################
# Variables used to assist docker tools and .yaml files during docker 
# container startups.
################################################################################
" | tee -a ${DEVOPS_FILE}

    print_variable_setting_instructions

    devops_add_config "${DEVOPS_FILE}" "PING_IDENTITY_ACCEPT_EULA"               "NO" "Do you accept the terms of license (found here: https://www.pingidentity.com/en/legal/subscription-agreement.html) with Ping Identity? (YES/NO)"
    devops_add_config "${DEVOPS_FILE}" "PING_IDENTITY_DEVOPS_USER"               ""                        "Ping Identity DevOps User (request here: https://bit.ly/ping-devops-request)"
    devops_add_config "${DEVOPS_FILE}" "PING_IDENTITY_DEVOPS_KEY"                ""                        "Ping Identity DevOps Key"
    devops_add_config "${DEVOPS_FILE}" "PING_IDENTITY_DEVOPS_HOME"               "${HOME}/projects/devops" "Location of Ping Identity DevOps repos and tools"
    devops_add_config "${DEVOPS_FILE}" "PING_IDENTITY_DEVOPS_REGISTRY"           "docker.io/pingidentity"  "Ping Identity DevOps Registry (recommend default: docker.io/pingidentity)"
    devops_add_config "${DEVOPS_FILE}" "PING_IDENTITY_DEVOPS_TAG"                "edge"                    "Ping Identity DevOps Tag (recommend default: edge)"

    echo "
################################################################################
#              Ping Identity DevOps Customized Variables
################################################################################
# Additional variables that you would like to send to containers via 
# docker-compose.yaml and kubernetes .yaml files.
#
# Examples include:
#     PING_CONTAINER_PRIVILEGED=false
#     PING_CONTAINER_UID=12345
#     PING_CONTAINER_GID=9876
#     LDAP_PORT=1389
#     LDAPS_PORT=1636
#     HTTPS_PORT=1443
#     JMX_PORT=1689
#     PING_IDENTITY_PASSWORD=2FederateM0re
#
# These are often set to nothing, unless you are using advanced features
################################################################################
" | tee -a ${DEVOPS_FILE}

    devops_add_config_custom "${DEVOPS_FILE}" "${_custom_variables}"   

    add_bash_aliases

    echo "

################################################################################
#
#  To run some sample Docker images, get more details with:
#
#    ping-devops docker
#
################################################################################
    "
}

########################################################################################################################
# base64-encode the provided string or file contents and remove any new lines (both line feeds and carriage returns).
#
# Arguments
#   ${1} -> The string to base-64 encode, or a file whose contents to base64-encode.
########################################################################################################################
base64_no_newlines() {
  if test -f "${1}"; then
    cat "${1}" | $BASE64 | tr -d '\r?\n'
  else
    echo -n "${1}" | $BASE64 | tr -d '\r?\n'
  fi
}

################################################################################
# main
################################################################################

#test -z "${1}" && usage

_ping_devops_command="${1}"

test -z "${_ping_devops_command}" && usage
test "${_ping_devops_command}" = "k8s" && _ping_devops_command="kubernetes"

case "${_ping_devops_command}" in
    config)
        shift
        devops_config
        ;;

    topic|topics)
        shift
        print_topic "${1}"
        ;;

    generate)
        shift
        _resource="${1}"
        shift
        _params="${*}"

        generate_resource "${_resource}" ${_params}
        ;;

    generate-profile)
        shift
        _product="${1}"
        shift
        _params="${*}"

        generate_profile "${_product}" ${_params}
        ;;

    docker|kubernetes)
        shift
        _orch_cmd="${1}"
        shift
        _product="${1}"
        shift
        _params="${*}"

        test -z "${_orch_cmd}" && usage_command "${_ping_devops_command}"

        case "${_orch_cmd}" in
            info|start|stop|rm|clean)
                orchestration_command "${_ping_devops_command}" "${_orch_cmd}" "${_product}" ${_params}
                ;;
            *) 
                usage_command "${_ping_devops_command}" "Unknown ${_ping_devops_command} command '${_orch_cmd}'"
        esac
        ;;

    info)
        shift
        _params="${*}"

        ping_devops_info ${_params}
        ;;
    version)
        shift
        _params="${*}"

        ping_devops_version ${_params}
        ;;
    *)
        usage "Unknown ping-devops command '${_ping_devops_command}'"
        ;;
esac


